- design-system/src/main/java/com/example/design_system/button/button.kt
- design-system/src/main/java/com/example/design_system/button/checkbox.kt
> 🔀 :: Dorm Notice

- design-system/src/main/java/com/example/design_system/dialog/dialog.kt
* Dorm의 Dialog를 구현하였습니다.
* DormCustomDialog를 통해 Dialog를 쉽게 만들 수 있습니다.
* DormSurveyDialog를 통해서 Dorm Style의 Dialog를 만들 수 있습니다.
> 🔀 :: DormDialog

- design-system/src/main/java/com/example/design_system/button/toggleswitch.kt
- design-system/src/main/java/com/example/design_system/component/survey.kt
- design-system/src/main/java/com/example/design_system/modifier/shadow.kt
> 🔀 :: DormSurvey

- design-system/src/main/java/com/example/design_system/component/notice.kt
> 🔀 :: DormNotice

- design-system/build.gradle.kts
- design-system/src/main/AndroidManifest.xml
- design-system/src/main/java/com/example/design_system/component/lostproperty.kt
> 🔀 :: DormLostProperty

- design-system/src/main/java/com/example/design_system/component/vote.kt
> 🔀 :: dorm vote

- design-system/src/main/java/com/example/design_system/animate/animationbox.kt
- design-system/src/main/java/com/example/design_system/component/photo.kt
- design-system/src/main/res/drawable/ic_photo_close.xml
> 🔀 :: DormPhoto

- auth_data/src/main/java/com/example/auth_data/remote/api/UserApi.kt
- auth_data/src/main/java/com/example/auth_data/remote/datasource/declaration/RemoteUserDataSource.kt
- auth_data/src/main/java/com/example/auth_data/remote/datasource/implementation/RemoteUserDataSourceImpl.kt
- auth_data/src/main/java/com/example/auth_data/remote/request/GetEmailCodeRequest.kt
- auth_data/src/main/java/com/example/auth_data/remote/request/RequestEmailCodeRequest.kt
- auth_data/src/main/java/com/example/auth_data/remote/url/DmsUrl.kt
- auth_data/src/main/java/com/example/auth_data/repository/UserRepositoryImpl.kt
- auth_domain/src/main/java/com/example/auth_domain/enum/EmailType.kt
- auth_domain/src/main/java/com/example/auth_domain/param/CheckEmailCodeParam.kt
- auth_domain/src/main/java/com/example/auth_domain/param/CompareEmailParam.kt
- auth_domain/src/main/java/com/example/auth_domain/param/RequestEmailCodeParam.kt
- auth_domain/src/main/java/com/example/auth_domain/repository/UserRepository.kt
- auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RefreshTokenUseCase.kt
- auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteCheckEmailUseCase.kt
- auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteCheckIdUseCase.kt
- auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteCompareEmailUseCase.kt
- auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteRequestEmailCodeUseCase.kt
- auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteSignInUseCase.kt
- auth_domain/src/main/java/com/example/auth_domain/usecase/auth/RemoteSignUpUseCase.kt
1차 스프린트 Auth 구현 
남은 Auth Business Logic 구현
> 🔀 :: (#49) Auth_Business_Logic

- presentation/src/main/java/com/example/dms_android/feature/auth/changepassword/ChangePasswordScreen.kt
- presentation/src/main/res/drawable/ic_baseline_arrow_back_24.xml
- presentation/src/main/res/values/strings.xml
> 🔀 :: (#56)First Sprint Change Password View

- design-system/src/main/java/com/example/design_system/component/lostproperty.kt
- design-system/src/main/java/com/example/design_system/component/notice.kt
- design-system/src/main/java/com/example/design_system/component/vote.kt
- design-system/src/main/java/com/example/design_system/icon/icons.kt
- design-system/src/main/java/com/example/design_system/textfield/textfield.kt
- design-system/src/main/java/com/example/design_system/typography/typography.kt
- presentation/src/main/java/com/example/dms_android/base/BaseViewModel.kt
- presentation/src/main/java/com/example/dms_android/feature/MainActivity.kt
- presentation/src/main/java/com/example/dms_android/feature/auth/login/LoginScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/auth/login/SignInEvent.kt
- presentation/src/main/java/com/example/dms_android/viewmodel/auth/login/SignInViewModel.kt
* Typography LineHeight 정의
* Typography Naming 변경
> Merge: (#61) update typography

- auth_data/src/main/java/com/example/auth_data/remote/api/ManagersApi.kt
- auth_data/src/main/java/com/example/auth_data/remote/datasource/declaration/RemoteStudentsDataSource.kt
- auth_data/src/main/java/com/example/auth_data/remote/datasource/implementation/RemoteStudentsDataSourceImpl.kt
- auth_data/src/main/java/com/example/auth_data/repository/StudentsRepositoryImpl.kt
- auth_domain/src/main/java/com/example/auth_domain/param/FindIdParam.kt
- auth_domain/src/main/java/com/example/auth_domain/repository/StudentsRepository.kt
- auth_domain/src/main/java/com/example/auth_domain/usecase/students/RemoteChangePasswordUseCase.kt
- auth_domain/src/main/java/com/example/auth_domain/usecase/students/RemoteFindIdUseCase.kt
- presentation/src/main/java/com/example/dms_android/feature/auth/changepassword/ChangePasswordEvent.kt
- presentation/src/main/java/com/example/dms_android/feature/auth/changepassword/ChangePasswordScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/auth/changepassword/ChangePasswordState.kt
- presentation/src/main/java/com/example/dms_android/feature/register/screen/ConfirmSchoolScreen.kt
- presentation/src/main/java/com/example/dms_android/viewmodel/changepw/ChangePasswordViewModel.kt
- presentation/src/main/res/values/strings.xml
> 🔀 :: (#59) First Sprint ChangePassword ViewModel

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/example/dms_android/feature/register/screen/ConfirmSchoolScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/register/screen/PolicyScreen.kt
- presentation/src/main/res/values/strings.xml
> 약관동의 화면 작업
- 약관동의 뷰를 작업합니다
- 웹뷰를 약관동의에 사용하였습니다(웹뷰 적용)
현재는 약관 webview가 나오지않아 임의로 다른 웹사이트를 넣어놓았습니다. 
학교 확인 질문 페이지의 Body6를 Caption으로 변경하였습니다.
> 🔀 :: FirstSprint Make Term View

- auth_domain/src/main/java/com/example/auth_domain/param/RegisterParam.kt
- presentation/src/main/java/com/example/dms_android/feature/register/event/SignUpEvent.kt
- presentation/src/main/java/com/example/dms_android/feature/register/state/SignUpState.kt
- presentation/src/main/java/com/example/dms_android/viewmodel/auth/register/SignUpViewModel.kt
> 회원가입 뷰모델을 작성해줍니다.
- SignUpState
- SignUpEvent
- SignUpViewModel
- RegisterParam
Param에 classRoom이 누락되어 넣어주었습니다.
> 🔀 :: FirstSprint   Make Register ViewModel

- auth_data/src/main/java/com/example/auth_data/repository/UserRepositoryImpl.kt
- auth_domain/src/main/java/com/example/auth_domain/param/CheckEmailCodeParam.kt
> 이메일 인증번호 확인 param값 수정
- 이메일 인증번호 확인 비즈니스 로직 중 다른param값이 들어가 수정해주었습니다.
trailing comma 붙혀줌
> 🔀 :: Confirm Email Authentication Number - diffrent param Value

- build.gradle.kts
- buildSrc/src/main/kotlin/Dependency.kt
- buildSrc/src/main/kotlin/ProjectProperties.kt
- buildSrc/src/main/kotlin/Versions.kt
- di/build.gradle.kts
- di/src/main/java/com/example/di/NetWorkModule.kt
- feature_data/build.gradle.kts
- gradle.properties
- local_database/build.gradle.kts
- presentation/build.gradle.kts
> 🔀 :: (#91) Develope Error Catching

- presentation/src/main/java/com/example/dms_android/feature/notice/NoticeDetailScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/notice/NoticeScreen.kt
- presentation/src/main/res/values/strings.xml
공지사항 리스트 뷰와 공지사항 자세히 보기 뷰를 완성하였습니다. 
디자인 시스템 덕분에 빨리 끝났습니다. 킹갓 디자인 시스템1!
> 🔀 :: (#105) Notice View

- design-system/src/main/java/com/example/design_system/modifier/clickable.kt
- presentation/src/main/java/com/example/dms_android/component/BottomSheetState.kt
- presentation/src/main/java/com/example/dms_android/feature/mypage/CheckOriginPwScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/mypage/MyPageChangePasswordScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/mypage/MyPageScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/notice/NoticeDetailScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/pointlist/PointList.kt
- presentation/src/main/java/com/example/dms_android/feature/pointlist/PointListScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/register/screen/last/ProfileImageScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/register/screen/password/SetPasswordScreen.kt
- presentation/src/main/java/com/example/dms_android/util/TopBar.kt
- presentation/src/main/res/values/strings.xml
4차 스프린트에 해당하는 모든 뷰를 구현하였습니다.
1. MyPage View
2. PointList View
3. Change Pw View
> 🔀 :: (#112) Four Sprint All View 

- design-system/src/main/java/com/example/design_system/color/colors.kt
- presentation/src/main/java/com/example/dms_android/feature/mypage/MyPageScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/pointlist/PointList.kt
> 🔀 :: (#135) Design Refactor

- auth_data/src/main/java/com/example/auth_data/remote/request/user/SignInRequest.kt
- auth_data/src/main/java/com/example/auth_data/remote/response/user/SignInResponse.kt
- auth_data/src/main/java/com/example/auth_data/remote/url/DmsUrl.kt
- auth_data/src/main/java/com/example/auth_data/repository/UserRepositoryImpl.kt
- auth_data/src/main/java/com/example/auth_data/util/HttpHandler.kt
- auth_data/src/main/java/com/example/auth_data/util/OfflineCacheUtil.kt
- auth_domain/src/main/java/com/example/auth_domain/entity/AuthInfoEntity.kt
- auth_domain/src/main/java/com/example/auth_domain/repository/UserRepository.kt
- auth_domain/src/main/java/com/example/auth_domain/usecase/user/RemoteSignInUseCase.kt
- buildSrc/src/main/kotlin/Versions.kt
- design-system/src/main/java/com/example/design_system/toast/ToastMaker.kt
- local_database/src/main/java/com/example/local_database/datasource/implementation/LocalUserDataSourceImpl.kt
- local_database/src/main/java/com/example/local_database/param/UserPersonalKeyParam.kt
- local_database/src/main/java/com/example/local_database/storage/declaration/UserDataStorage.kt
- local_database/src/main/java/com/example/local_database/storage/implementation/UserDataStorageImpl.kt
- local_database/src/main/java/com/example/local_database/util/LocalDateTimePraser.kt
- local_domain/src/main/java/com/example/local_domain/entity/UserVisibleLocalEntity.kt
- presentation/build.gradle.kts
- presentation/src/main/java/com/example/dms_android/feature/MainActivity.kt
- presentation/src/main/java/com/example/dms_android/feature/auth/login/LoginScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/auth/login/SignInEvent.kt
- presentation/src/main/java/com/example/dms_android/feature/auth/login/SignInViewEffect.kt
- presentation/src/main/java/com/example/dms_android/feature/navigator/BottomNavigationItem.kt
- presentation/src/main/java/com/example/dms_android/feature/navigator/DmsApp.kt
- presentation/src/main/java/com/example/dms_android/feature/navigator/NavigationRoute.kt
- presentation/src/main/java/com/example/dms_android/feature/navigator/RootDms.kt
- presentation/src/main/java/com/example/dms_android/feature/notice/NoticeViewModel.kt
- presentation/src/main/java/com/example/dms_android/viewmodel/auth/login/SignInViewModel.kt
LoginViewModel 작성 예외처리
진짜 개어려웠다.. 내가 짠 코드중에 제일 어려웠다.
_No response_
> 🔀 :: (#147) LoginViewModel & Test

- design-system/src/main/java/com/example/design_system/component/seat.kt
- design-system/src/main/java/com/example/design_system/constans/constraints.kt
- design-system/src/main/java/com/example/design_system/modifier/shadow.kt
- design-system/src/main/java/com/example/design_system/typography/typography.kt
자습실 좌석 컴포넌트입니다.
사용 방법은 Preview와 KDoc을 참고해주세요.
> 🔀 :: (#160) 자습실 좌석 컴포넌트

- data/src/main/java/com/example/data/remote/api/StudyRoomApi.kt
- data/src/main/java/com/example/data/remote/datasource/declaration/RemoteStudyRoomDataSource.kt
- data/src/main/java/com/example/data/remote/datasource/implementation/RemoteStudyRoomDataSourceImpl.kt
- data/src/main/java/com/example/data/remote/response/studyroom/ApplySeatTimeResponse.kt
- data/src/main/java/com/example/data/remote/response/studyroom/StudyRoomDetailResponse.kt
- data/src/main/java/com/example/data/remote/response/studyroom/StudyRoomListResponse.kt
- data/src/main/java/com/example/data/remote/response/studyroom/StudyRoomTypeResponse.kt
- data/src/main/java/com/example/data/remote/url/DmsUrl.kt
- data/src/main/java/com/example/data/repository/StudyRoomRepositoryImpl.kt
- data/src/main/java/com/example/data/util/OfflineCacheUtil.kt
- di/src/main/java/com/example/di/NetWorkModule.kt
- di/src/main/java/com/example/di/RemoteDataSourceModule.kt
- di/src/main/java/com/example/di/RepositoryModule.kt
- domain/src/main/java/com/example/domain/entity/studyroom/ApplySeatTimeEntity.kt
- domain/src/main/java/com/example/domain/entity/studyroom/StudyRoomDetailEntity.kt
- domain/src/main/java/com/example/domain/entity/studyroom/StudyRoomListEntity.kt
- domain/src/main/java/com/example/domain/entity/studyroom/StudyRoomTypeEntity.kt
- domain/src/main/java/com/example/domain/repository/StudyRoomRepository.kt
- domain/src/main/java/com/example/domain/usecase/studyroom/RemoteApplySeatUseCase.kt
- domain/src/main/java/com/example/domain/usecase/studyroom/RemoteCancelApplySeat.kt
- domain/src/main/java/com/example/domain/usecase/studyroom/RemoteFetchApplySeatUseCase.kt
- domain/src/main/java/com/example/domain/usecase/studyroom/RemoteFetchStudyRoomDetailUseCase.kt
- domain/src/main/java/com/example/domain/usecase/studyroom/RemoteFetchStudyRoomListUseCase.kt
- domain/src/main/java/com/example/domain/usecase/studyroom/RemoteFetchStudyRoomTypeUseCase.kt
- local_database/src/main/java/com/example/local_database/dao/StudyRoomDao.kt
- local_database/src/main/java/com/example/local_database/database/DMSDataBase.kt
- local_database/src/main/java/com/example/local_database/datasource/declaration/LocalStudyRoomDataSource.kt
- local_database/src/main/java/com/example/local_database/datasource/implementation/LocalStudyRoomDataSourceImpl.kt
- local_database/src/main/java/com/example/local_database/entity/studyroom/FetchApplyTimeRoomEntity.kt
> 자습실 목록, 자습실 상세보기, 자리 종류보기 비즈니스 로직  구현
- 자습실 목록, 자습실 상세보기, 자리 종류보기 비즈니스 로직  구현합니다.
part1먼저 머지하고 part2 머지 필요함
총 자습실 로직 6개 중 6개 완
일단 작업이 급하기 때문에 remoteFlow만 emit하게 했고 나중에 pr 파서 캐싱 로직 작성하겠습니다.
> 🔀 :: (#157) Implementation of a study room list, detail, and place type view - part2 

- data/src/main/java/com/example/data/remote/api/StudyRoomApi.kt
- data/src/main/java/com/example/data/remote/datasource/declaration/RemoteStudyRoomDataSource.kt
- data/src/main/java/com/example/data/remote/datasource/implementation/RemoteStudyRoomDataSourceImpl.kt
- data/src/main/java/com/example/data/remote/response/studyroom/ApplySeatTimeResponse.kt
- data/src/main/java/com/example/data/remote/url/DmsUrl.kt
- data/src/main/java/com/example/data/repository/StudyRoomRepositoryImpl.kt
- data/src/main/java/com/example/data/util/OfflineCacheUtil.kt
- di/src/main/java/com/example/di/NetWorkModule.kt
- di/src/main/java/com/example/di/RemoteDataSourceModule.kt
- di/src/main/java/com/example/di/RepositoryModule.kt
- domain/src/main/java/com/example/domain/entity/studyroom/ApplySeatTimeEntity.kt
- domain/src/main/java/com/example/domain/repository/StudyRoomRepository.kt
- domain/src/main/java/com/example/domain/usecase/studyroom/RemoteApplySeatUseCase.kt
- domain/src/main/java/com/example/domain/usecase/studyroom/RemoteCancelApplySeat.kt
- domain/src/main/java/com/example/domain/usecase/studyroom/RemoteFetchApplySeatUseCase.kt
- local_database/src/main/java/com/example/local_database/dao/StudyRoomDao.kt
- local_database/src/main/java/com/example/local_database/database/DMSDataBase.kt
- local_database/src/main/java/com/example/local_database/datasource/declaration/LocalStudyRoomDataSource.kt
- local_database/src/main/java/com/example/local_database/datasource/implementation/LocalStudyRoomDataSourceImpl.kt
- local_database/src/main/java/com/example/local_database/entity/studyroom/FetchApplyTimeRoomEntity.kt
> 자습실 자리 신청
자습실 신청 시간 보기
자습실 자리 신청 취소
비즈니스 로직을 작성합니다.
- 자습실 자리 신청
자습실 신청 시간 보기
자습실 자리 신청 취소 remote비즈니스 로직을 작성했습니다.
DI에 자습실 관련 di코드를 작성하였습니다.
총 자습실 로직 6개 중 3개 완
일단 작업이 급하기 때문에 remoteFlow만 emit하게 했고 나중에 pr 파서 캐싱 로직 작성하겠습니다.
> 🔀 :: (#155) Implement Apply for a study room, cancel, and view the time business Logic

- data/src/main/java/com/example/data/intercepter/AuthorizationInterceptor.kt
- data/src/main/java/com/example/data/remote/response/mypage/FetchPointListResponse.kt
- data/src/main/java/com/example/data/repository/UserRepositoryImpl.kt
- domain/src/main/java/com/example/domain/entity/mypage/PointListEntity.kt
- domain/src/main/java/com/example/domain/param/LoginParam.kt
- domain/src/main/java/com/example/domain/repository/UserRepository.kt
- domain/src/main/java/com/example/domain/usecase/user/AutoLoginUseCase.kt
- local_database/src/main/java/com/example/local_database/datasource/declaration/LocalUserDataSource.kt
- local_database/src/main/java/com/example/local_database/datasource/implementation/LocalUserDataSourceImpl.kt
- local_database/src/main/java/com/example/local_database/param/user/UserInfoParam.kt
- local_database/src/main/java/com/example/local_database/storage/declaration/UserDataStorage.kt
- local_database/src/main/java/com/example/local_database/storage/implementation/UserDataStorageImpl.kt
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/example/dms_android/feature/MainActivity.kt
- presentation/src/main/java/com/example/dms_android/feature/auth/login/LoginScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/auth/login/SignInState.kt
- presentation/src/main/java/com/example/dms_android/feature/navigator/RootDms.kt
- presentation/src/main/java/com/example/dms_android/feature/splash/Splash.kt
- presentation/src/main/java/com/example/dms_android/feature/splash/SplashActivity.kt
- presentation/src/main/java/com/example/dms_android/feature/splash/SplashViewModel.kt
- presentation/src/main/java/com/example/dms_android/viewmodel/auth/login/SignInViewModel.kt
- presentation/src/main/java/com/example/dms_android/viewmodel/mypage/MyPageViewModel.kt
> 🔀 (#171) auto login

- design-system/src/main/java/com/example/design_system/component/bottomsheet.kt
- design-system/src/main/java/com/example/design_system/component/calender.kt
- presentation/src/main/java/com/example/dms_android/util/compose/DormImageUploadLayout.kt
- presentation/src/main/java/com/example/dms_android/util/covert/FileUtil.kt
- presentation/src/main/java/com/example/dms_android/util/covert/UriUtil.kt
- presentation/src/main/java/com/example/dms_android/util/covert/bitmap.kt
- presentation/src/main/res/drawable/ic_mypage_edit.xml
DormBottomSheet 작업
DormCalender 작업
각종 converter
DormImageUploadLayout
> 🔀 :: (#169) Update Design System

- data/src/main/java/com/example/data/remote/api/NoticeApi.kt
- data/src/main/java/com/example/data/remote/datasource/declaration/RemoteNoticeDataSource.kt
- data/src/main/java/com/example/data/remote/datasource/implementation/RemoteNoticeDataSourceImpl.kt
- data/src/main/java/com/example/data/repository/NoticeRepositoryImpl.kt
- domain/src/main/java/com/example/domain/repository/NoticeRepository.kt
- domain/src/main/java/com/example/domain/usecase/notice/RemoteCheckNewNoticeBooleanUseCase.kt
- presentation/src/main/java/com/example/dms_android/feature/notice/NoticeScreen.kt
- presentation/src/main/java/com/example/dms_android/feature/register/state/home/MealState.kt
- presentation/src/main/java/com/example/dms_android/viewmodel/home/MealViewModel.kt
> 🔀 :: (#168) view part error refactoring

- design-system/src/main/java/com/example/design_system/component/seat.kt
> 🔀 :: (#176) SeatTypeList

- presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/apply/ApplicationMainScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/navigator/BottomNavigationItem.kt
- presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
- presentation/src/main/java/team/aliens/dms_android/feature/navigator/NavigationRoute.kt
- presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootDms.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
- presentation/src/main/res/values/strings.xml
> 신청 메인 화면을 구현하고 관련 로직을 작성했습니다.
- 신청 메인 화면 구현
- Navigation 자습실 신청 화면 -> 신청 메인 화면으로 교체
- 신청 메인 화면에서 자습실 화면으로 navigate 기능 구현
- StudyRoomListScreen 에서 TopBar , back stack 기능 구현
- 마지막 신청 항목 표시 기능 구현
- 작업을 하며 디자인과 일치하지 않는 몇몇 부분을 발견했습니다.
- 이슈 생성하여 수정할 계획입니다.
> 🔀 :: (#192) Implement application apply main screen

- design-system/src/main/java/team/aliens/design_system/typography/typography.kt
- presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeDetailScreen.kt
- presentation/src/main/java/team/aliens/dms_android/util/TopBar.kt
> 디자인과 일치하지 않는 텍스트 스타일을 수정하였습니다.
- typography subtitle2 font weight 변경
- 잔류 신청 화면 Text -> 디자인 시스템 텍스트로 변경
- top bar text style 변경
- 공지 생성일자 텍스트 색 변경
- Notice background color 변경
Closes #194
> 🔀 :: (#194) edit design system typography

- presentation/src/main/java/team/aliens/dms_android/feature/StayApplicationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/util/TopBar.kt
> 탑바를 리팩토링 했습니다.
- padding horizontal 을 Spacer 로 변경
- 아이콘 클릭 ripple 효과 제거
- Closes #195
> 🔀 :: (#195) top bar refactoring

- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomState.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomViewModel.kt
- presentation/src/main/res/values/strings.xml
> 자습실과 관련된 뷰를 리팩토링합니다
- 자습실과 관련된 스트링 리소스를 추가하였습니다
- 자습실 뷰모델 로직을 재구성하였습니다
- 자습실 목록 스크린을 재구성하였습니다
> 🔀 :: (#214) refactor studyroom view

- data/src/main/java/team/aliens/data/intercepter/AuthorizationInterceptor.kt
- data/src/main/java/team/aliens/data/remote/api/UserApi.kt
- data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteUserDataSource.kt
- data/src/main/java/team/aliens/data/remote/datasource/implementation/RemoteUserDataSourceImpl.kt
- data/src/main/java/team/aliens/data/remote/url/DmsUrl.kt
- data/src/main/java/team/aliens/data/repository/UserRepositoryImpl.kt
- design-system/src/main/java/team/aliens/design_system/dialog/dialog.kt
- di/src/main/java/team/aliens/di/NetWorkModule.kt
- domain/src/main/java/team/aliens/domain/repository/UserRepository.kt
- domain/src/main/java/team/aliens/domain/usecase/user/AutoSignInUseCase.kt
- domain/src/main/java/team/aliens/domain/usecase/user/ReissueTokenUseCase.kt
- domain/src/main/java/team/aliens/domain/usecase/user/SignOutUseCase.kt
- local_database/src/main/java/team/aliens/local_database/datasource/declaration/LocalUserDataSource.kt
- local_database/src/main/java/team/aliens/local_database/datasource/implementation/LocalUserDataSourceImpl.kt
- local_database/src/main/java/team/aliens/local_database/storage/declaration/UserDataStorage.kt
- local_database/src/main/java/team/aliens/local_database/storage/implementation/UserDataStorageImpl.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/login/SignInState.kt
- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/splash/SplashViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/auth/login/SignInViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/mypage/MyPageViewModel.kt
> 로그인 로직을 재구성하고, 로그아웃 로직 및 다이얼로그를 구현합니다
- 로그인 로직 재구성
- 기존 : 새로 로그인 -> 수정 : 토큰 재발급
- 로그아웃 로직 구현
- 로그아웃 다이얼로그 구현
> 🔀 :: (#215) refactor login logicimplement logout

- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/mypage/MyPageViewModel.kt
- presentation/src/main/res/values/strings.xml
> MyPageScreen을 리팩터링합니다
- MyPageScreen 리팩터링
- MyPageViewModel 로직 변경
> 🔀 :: (#222) refactor MyPageScreen

- design-system/src/main/java/team/aliens/design_system/button/basicbutton.kt
- design-system/src/main/java/team/aliens/design_system/button/checkbox.kt
- design-system/src/main/java/team/aliens/design_system/textfield/textfield.kt
- design-system/src/main/java/team/aliens/design_system/typography/typography.kt
- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageChangePasswordScreen.kt
> 로그인 화면에서 디자인과 다른 컴포넌트들들 의 디자인 시스템을 수정했습니다.
- DormTextField focused 구현
- 디자인 시스템 있지만 코드 상으로 없는 typography 생성
- DormTextField textstyle 변경
- DormTextField error 처리 로직 변경
- 디자인 시스템 상에서는 변경했지만 로그인 화면에서 반영하지 않은 컴포넌트들을 수정해야 합니다.
- Closes #225
> 🔀 :: (#225) refactoring login screen design system component

- presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationScreen.kt
- presentation/src/main/res/values-night/themes.xml
> 앱 다크 테마 적용시 보이는 top bar 제거 및 신청 화면들들 리팩토링
- DarkActionBar 제거
- Dark status bar 색상 변경
- Application Screen 신청 항목과 신청 항목 이름 정렬
- Remain Application Screen 배경 색 설정
Close #228
> 🔀 :: (#228) remove top bar in dark theme and refactoring application screens

- data/src/main/java/team/aliens/data/remote/response/mypage/FetchPointListResponse.kt
- data/src/main/java/team/aliens/data/repository/MyPageRepositoryImpl.kt
- domain/src/main/java/team/aliens/domain/entity/mypage/PointListEntity.kt
- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageState.kt
- presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointList.kt
- presentation/src/main/java/team/aliens/dms_android/feature/pointlist/PointListScreen.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/mypage/MyPageViewModel.kt
> 상벌점 조회 기능을 구현합니다
- 상벌점 조회 기능 구현
- 상벌점 뷰 리팩토링
> 🔀 :: (#243) implement plusminus point detail logic

- data/src/main/java/team/aliens/data/remote/api/StudyRoomApi.kt
- data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteStudyRoomDataSource.kt
- data/src/main/java/team/aliens/data/remote/datasource/implementation/RemoteStudyRoomDataSourceImpl.kt
- data/src/main/java/team/aliens/data/remote/response/studyroom/CurrentStudyRoomOptionResponse.kt
- data/src/main/java/team/aliens/data/remote/url/DmsUrl.kt
- data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
- domain/src/main/java/team/aliens/domain/entity/studyroom/CurrentStudyRoomOptionEntity.kt
- domain/src/main/java/team/aliens/domain/repository/StudyRoomRepository.kt
- domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteFetchCurrentStudyRoomOptionUseCase.kt
- presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomViewModel.kt
> 내 자습실 신청 항목 보기 기능을 구현했습니다.
- DmsUrl 에 url study-rooms/my url 추가
- datasource, repository, viewmodel fetchCurrentStudyRoomOption 함수 추가
- fetchCurrentStudyRoomOption usecase 추가
- ApplicatoinScreen 에서 이벤트 처리 및 값 띄워주기 로직 추가
> 🔀 :: (#251) implement fetch current study room option logic

- data/src/main/java/team/aliens/data/repository/MyPageRepositoryImpl.kt
> 머지된 PR에서 반영되지 않은 내용을 반영합니다
- 로그를 제거합니다
> 🔀 :: (#255) remove log

- presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
> android 8.0 버전 테스트를 하였습니다. 
- 8.0 실행 시 네비게이션 icon 크기가 달라지는 오류를 해결
> 🔀 :: (#245) android 8.0 compatibility test

- data/src/main/java/team/aliens/data/remote/api/StudentsApi.kt
- data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteStudentsDataSource.kt
- data/src/main/java/team/aliens/data/remote/datasource/implementation/RemoteStudentsDataSourceImpl.kt
- data/src/main/java/team/aliens/data/remote/url/DmsUrl.kt
- data/src/main/java/team/aliens/data/repository/StudentsRepositoryImpl.kt
- domain/src/main/java/team/aliens/domain/repository/StudentsRepository.kt
- domain/src/main/java/team/aliens/domain/usecase/students/RemoteStudentWithdrawUseCase.kt
- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/mypage/MyPageViewModel.kt
- presentation/src/main/res/values/strings.xml
> 회원 탈퇴를 구현합니다
- 마이페이지 일부 리팩토링
- 회원 탈퇴 구현
> 🔀 :: (#262) implement withdrawal

- data/src/main/java/team/aliens/data/remote/api/StudyRoomApi.kt
- domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteCancelApplySeatUseCase.kt
- domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteFetchStudyRoomApplicationTimeUseCase.kt
- presentation/src/main/java/team/aliens/dms_android/_base/BaseEvent.kt
- presentation/src/main/java/team/aliens/dms_android/_base/BaseUiState.kt
- presentation/src/main/java/team/aliens/dms_android/_base/BaseViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/_base/ErrorEvent.kt
- presentation/src/main/java/team/aliens/dms_android/base/BaseViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListUiState.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/util/Extensions.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailUiState.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
- presentation/src/main/res/values/strings.xml
> 자습실 신청 관련 버그를 리팩토링합니다
- 자습실 관련 버그를 수정합니다
- 오류 핸들링 로직을 구현합니다
- BaseViewModel 컴포넌트를 새로 구현합니다
> 🔀 :: (#246) refactor and fix bugs related to study room

- di/src/main/java/team/aliens/di/NetWorkModule.kt
> BASE URL을 dms 도메인으로 변경합니다
- BASE URL 변경
> 🔀 :: (#267) change base url

- buildSrc/src/main/kotlin/ProjectProperties.kt
- data/src/main/java/team/aliens/data/util/HttpRequestHandler.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> 안드로이드 8.0의 호환성을 추가합니다
- 최소 api level 변경
- 자습실 신청 로직 일부 변경
> 🔀 :: (#270) add compatibility on android 80

- presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
- presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
> 바텀 네비게이션에 잘못된 아이콘이 유지되는 버그를 수정합니다
- 바텀네비게이션 관련 아이템 표시 로직 구현
> 🔀 :: (#277) make bottom tab selected item changes by screen

- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
> 자습실 시간별 필터를 일시적으로 비활성화합니다
- 자습실 시간별 필터 비활성화
> 🔀 :: (#274) disable study room filter temporarily

- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageState.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/mypage/MyPageViewModel.kt
> 마이페이지에 접근했을 때, 자동으로 정보가 불러와지지 않는 버그를 수정합니다
- 마이페이지 및 뷰모델 리팩토링
> 🔀 :: (#276) implement my page information auto-fetching

- presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealContent.kt
- presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealState.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/home/MealViewModel.kt
> 앱 로그인 후 처음 진입 시 급식 정보가 표시되지 않는 로직을 수정합니다
- 급식 정보 조회 로직을 재구성합니다
프로젝트가 너무 더러워요
> 🔀 :: (#247) meals dont show when first sign in into app

- design-system/src/main/java/team/aliens/design_system/component/notice.kt
- presentation/src/main/java/team/aliens/dms_android/feature/image/ConfirmImageScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt
- presentation/src/main/res/values/strings.xml
> 공지 조회 로직을 재구성합니다
- 공지 조회 로직 재구성
> 🔀 :: (#282) refactor fetching notices logic

- presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeDetailScreen.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/notice/NoticeViewModel.kt
> 공지 상세보기 화면에서 상세 화면이 제대로 업데이트되지 않는 버그를 수정합니다
- 공지 상세보기 화면에서 자동으로 공지 상세가 업데이트되도록 리팩토링
> 🔀 :: (#289) refactor NoticeDetailScreen

- data/src/main/java/team/aliens/data/intercepter/AuthorizationInterceptor.kt
- data/src/main/java/team/aliens/data/repository/UserRepositoryImpl.kt
- domain/src/main/java/team/aliens/domain/repository/UserRepository.kt
- domain/src/main/java/team/aliens/domain/usecase/user/FetchAutoSignInOptionUseCase.kt
- presentation/src/main/java/team/aliens/dms_android/feature/splash/RootViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/feature/splash/SplashScreen.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/root/RootViewModel.kt
> 로그아웃 로직을 리팩토링합니다
- 로그아웃 로직 리팩토링
- 로그아웃 시 튕기는 버그 픽스
자동 로그인 재구현 필요해요
> 🔀 :: (#288) refactor sign out

- data/src/main/java/team/aliens/data/intercepter/AuthorizationInterceptor.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListUiState.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailUiState.kt
…s as null
> 자습실 신청 시간이 null로 표시되는 버그를 수정합니다
-
> 🔀 :: (#292) fix error related to studyroom, and fix interceptor

- design-system/src/main/java/team/aliens/design_system/textfield/textfield.kt
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/team/aliens/dms_android/feature/application/ApplicationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealContent.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/ApplicationViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/auth/login/SignInViewModel.kt
- presentation/src/main/res/values-night/themes.xml
- presentation/src/main/res/values/themes.xml
> 사용자 편의 기능을 구현합니다
- 급식 페이저 진동 추가
- 로그인 다중 처리 방지
> 🔀 :: (#303) 사용자 편의 기능 구현

- data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
- design-system/src/main/java/team/aliens/design_system/component/seat.kt
- domain/src/main/java/team/aliens/domain/entity/studyroom/SeatTypeEntity.kt
- domain/src/main/java/team/aliens/domain/repository/StudyRoomRepository.kt
- domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteFetchStudyRoomSeatTypeUseCase.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailUiState.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
자습실 상세보기의 자리 타입을 가르쳐 주는 RowList를 만들었습니다.
-
> 🔀 :: (#296) StudyRoom SeatType

- presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
> 급식 조회 시 날짜 정보를 함께 제공하는 로직을 구현합니다
-
> 🔀 :: (#312) implement showing today's day of week in korean on CafeteriaScreen

- data/src/main/java/team/aliens/data/remote/api/NoticeApi.kt
- data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteNoticeDataSource.kt
- data/src/main/java/team/aliens/data/remote/datasource/implementation/RemoteNoticeDataSourceImpl.kt
- data/src/main/java/team/aliens/data/repository/NoticeRepositoryImpl.kt
- domain/src/main/java/team/aliens/domain/repository/NoticeRepository.kt
- domain/src/main/java/team/aliens/domain/usecase/notice/RemoteCheckNewNoticeBooleanUseCase.kt
- presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/notice/NoticeViewModel.kt
> 새로운 공지사항 확인 로직 반환 타입을 Boolean 에서 Response / Entity 로 감싸주었습니다
- 급식 화면에서 애니메이션 구현
> 🔀 :: (#315) fetch has new notice

- presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordIdentificationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/comparepassword/ComparePasswordScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/findid/FindIdScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageChangePasswordScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/id/SignUpIdScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/password/SignUpPasswordScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/SignUpSchoolQuestionScreen.kt
> 키보드가 사용되는 화면에서 편의 기능을 구현하였습니다.
- 키보드 완료 / 포커스 전환 액션 추가
- 남은 할 일
- textfield 에 인증 번호 입력 textfield 추가하기
- 로그인 후 프로필 수정 이미지 표시 버그 수정하기
- textfield 입력 항목 trim() 으로 처리하기
- 회원가입 로직 리팩토링 하기
> 🔀 :: (#323) keyboard button action

- presentation/src/main/AndroidManifest.xml
> 화면 회전을 했을 때 회전이 되는 것을 수정했습니다.
-
> 🔀 :: (#326) 화면 회전 방지 구현

- presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordIdentificationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordVerifyEmailScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/findid/FindIdScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageChangePasswordScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailVerifyScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/id/SignUpIdScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SignUpPolicyScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SignUpProfileScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/password/SignUpPasswordScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/SignUpSchoolQuestionScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/SignUpVerifySchoolScreen.kt
- presentation/src/main/java/team/aliens/dms_android/util/VerifyTime.kt
- presentation/src/main/res/values/strings.xml
> 키보드 액션 관련 로직 및 회원가입 프로필 설정 로직을 리팩토링 하였습니다.
- 회원가입 이미지 null 처리
- 키보드 사용 스크린에서 관련 로직 리팩토링
> 🔀 :: (#323) keyboard button action && signup profile logic refactoring

- presentation/src/main/res/values/strings.xml
> 파스칼 케이스였던 스트링 리소스를 스네이크 케이스로 바꾸는 작업을 했습니다.
- 파스칼 케이스 -> 스네이크 케이스
> 🔀 :: (#340) 스트링 리소스 표기법 변경

- design-system/src/main/java/team/aliens/design_system/animate/animationbox.kt
- design-system/src/main/java/team/aliens/design_system/annotation/DormDeprecated.kt
- design-system/src/main/java/team/aliens/design_system/button/button.kt
- design-system/src/main/java/team/aliens/design_system/button/checkbox.kt
- design-system/src/main/java/team/aliens/design_system/button/radiobutton.kt
- design-system/src/main/java/team/aliens/design_system/button/toggleswitch.kt
- design-system/src/main/java/team/aliens/design_system/color/colors.kt
- design-system/src/main/java/team/aliens/design_system/component/bottomsheet.kt
- design-system/src/main/java/team/aliens/design_system/component/calender.kt
- design-system/src/main/java/team/aliens/design_system/component/lostproperty.kt
- design-system/src/main/java/team/aliens/design_system/component/notice.kt
- design-system/src/main/java/team/aliens/design_system/component/photo.kt
- design-system/src/main/java/team/aliens/design_system/component/seat.kt
- design-system/src/main/java/team/aliens/design_system/component/survey.kt
- design-system/src/main/java/team/aliens/design_system/component/vote.kt
- design-system/src/main/java/team/aliens/design_system/dialog/dialog.kt
- design-system/src/main/java/team/aliens/design_system/icon/icons.kt
- design-system/src/main/java/team/aliens/design_system/modifier/background.kt
- design-system/src/main/java/team/aliens/design_system/modifier/clickable.kt
- design-system/src/main/java/team/aliens/design_system/modifier/shadow.kt
- design-system/src/main/java/team/aliens/design_system/textfield/textfield.kt
- design-system/src/main/java/team/aliens/design_system/theme/theme.kt
- design-system/src/main/java/team/aliens/design_system/typography/typography.kt
* 기존 컴포넌트들을 Deprecated 합니다.
* 기존 Deprecated를 사용하면 IDE딴에서 밑줄이 그어져, 불편할 수 있을 것 같아 추후에 DDS(DMS Design System)으로 교체된다는걸 명시적으로 표현하기 위해 어노테이션을 사용합니다.
> 🔀 :: (#345) deprecated design system

- data/src/main/java/team/aliens/data/remote/api/StudyRoomApi.kt
- data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteStudyRoomDataSource.kt
- data/src/main/java/team/aliens/data/remote/datasource/implementation/RemoteStudyRoomDataSourceImpl.kt
- data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
- design-system/src/main/java/team/aliens/design_system/component/seat.kt
- domain/src/main/java/team/aliens/domain/repository/StudyRoomRepository.kt
- domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteFetchStudyRoomSeatTypeUseCase.kt
- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/ApplicationViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
> 자리 종류 보기 api 에 study room id를 추가했습니다.
- 자리 종류 보기 api 에 study room id 파라미터 추가
- seat content 넘버 색 변경
- 마지막 신청 항목 확인 버그 수정
> 🔀 :: (#351) 자리 종류 보기 리팩토링

- buildSrc/src/main/kotlin/ProjectProperties.kt
> ⚡️ :: 버전 업데이트

- data/src/main/java/team/aliens/data/remote/response/studyroom/StudyRoomDetailResponse.kt
- data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
- domain/src/main/java/team/aliens/domain/entity/studyroom/StudyRoomDetailEntity.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomState.kt
- presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailUiState.kt
> 자습실 앱 바 이용시간 표시 로직을 구현했습니다.
- startTime endTime 파라미터 추가
> 🔀 :: (#362) 자습실 앱 바 이용시간 표시 로직 구현

- .github/workflows/ci.yml
> 🔀 :: (#365) ci PROD_BASE_URL 구현

- buildSrc/src/main/kotlin/ProjectProperties.kt
- presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
- presentation/src/main/java/team/aliens/dms_android/feature/MainActivity.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
> #367 과 동일한 작업이며, 버전 업데이트만 존재합니다.
-
> 🔀 :: (#369) 로그인 화면에서 메인 화면으로 진입할 시 앱이 튕기는 오류 수정 버전 배포

- buildSrc/src/main/kotlin/ProjectProperties.kt
> 플레이 스토어 배포 버전을 1.1.0으로 업데이트합니다
- buildSrc 모듈 수정
> 🔀 :: (#378) 버전 업데이트

- design-system/src/main/java/team/aliens/design_system/toast/toast.kt
- presentation/src/main/java/team/aliens/dms_android/feature/MainActivity.kt
- presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootDms.kt
> Scaffold State 를 사용하여 toast 를 구현하였습니다.
- DormToastHost
- DormToast
- 구현
> 🔀 :: (#394) 전역 토스트 관리 기능 구현

- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomsScreen.kt
- presentation/src/main/res/values/strings.xml
> 자습실 패키지 screen 리팩토링을 합니다.
- string 수정
- screen 함수 분리 작업
- 예외 처리 rebase한 코드로 수정
> 🔀 :: (#407) 자습실 패키지 screen 리팩토링

- design-system/src/main/java/team/aliens/design_system/toast/toast.kt
- presentation/src/main/java/team/aliens/dms_android/ToastManager.kt
- presentation/src/main/java/team/aliens/dms_android/feature/application/DmsAppState.kt
- presentation/src/main/java/team/aliens/dms_android/util/manager/DialogManager.kt
- presentation/src/main/java/team/aliens/dms_android/util/manager/ToastManager.kt
> toastmanager 내부 로직 및 dialog manager 를 구현했습니다.
- toast state flow 구현
- dialog manager 구현
- toast manager manager 패키지로 이동
- dialog manager 추가적인 구현이 필요하여 이슈를 남겨놓았습니다.
> 🔀 :: (#406) dmsappstate 구현

- data/src/main/java/team/aliens/data/datasource/local/LocalAuthDataSource.kt
- data/src/main/java/team/aliens/data/facade/AuthorizationFacade.kt
- data/src/main/java/team/aliens/data/manager/TokenReissueManager.kt
- data/src/main/java/team/aliens/data/repository/AuthRepositoryImpl.kt
- data/src/main/java/team/aliens/data/util/DateUtil.kt
- data/src/main/java/team/aliens/data/util/TokenReissueManager.kt
- design-system/src/main/java/team/aliens/design_system/toast/toast.kt
- di/src/main/java/team/aliens/di/facade/FacadeModule.kt
- di/src/main/java/team/aliens/di/manager/ManagerModule.kt
- di/src/main/java/team/aliens/di/remote/HttpModule.kt
- local/src/main/java/team/aliens/local/datasource/LocalAuthDataSourceImpl.kt
- presentation/src/main/java/team/aliens/dms_android/feature/MainActivity.kt
- presentation/src/main/java/team/aliens/dms_android/feature/application/DmsAppState.kt
- presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt
- presentation/src/main/java/team/aliens/dms_android/handler/DmsExceptionHandler.kt
- remote/src/main/java/team/aliens/remote/http/AuthorizationInterceptor.kt
- remote/src/main/java/team/aliens/remote/http/TokenReissueClient.kt
- remote/src/main/java/team/aliens/remote/http/TokenReissueManagerImpl.kt
> AuthorizationInterceptor를 수정합니다
- AuthorizationFacade 수정
- AuthorizationInterceptor 수정
- TokenReissueManager/impl 구현
- Thread defaultExceptionHandler 설정
> 🔀 :: (#427) authorizationinterceptor 수정

- presentation/src/main/java/team/aliens/dms_android/base/BaseMviViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/base/MviIntent.kt
- presentation/src/main/java/team/aliens/dms_android/base/MviSingleEvent.kt
- presentation/src/main/java/team/aliens/dms_android/base/MviViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/base/MviViewState.kt
- presentation/src/main/java/team/aliens/dms_android/base/UiEvent.kt
- presentation/src/main/java/team/aliens/dms_android/base/UiState.kt
> MviViewModel을 구현합니다
- Side Effect 개념이 추가된 ViewModel을 구현하였습니다
> 🔀 :: (#444) mvi viewmodel 구현

- buildSrc/src/main/kotlin/ProjectProperties.kt
- design-system/src/main/java/team/aliens/design_system/modifier/shadow.kt
- domain/src/main/java/team/aliens/domain/model/_common/DayOfWeek.kt
- domain/src/main/java/team/aliens/domain/model/remains/FetchRemainsApplicationTimeOutput.kt
- domain/src/main/java/team/aliens/domain/model/remains/RemainsApplicationTime.kt
- presentation/src/main/java/team/aliens/dms_android/DmsApp.kt
- presentation/src/main/java/team/aliens/dms_android/DmsAppState.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/signin/SignInScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/home/Home.kt
- presentation/src/main/java/team/aliens/dms_android/feature/home/HomeNavigation.kt
- presentation/src/main/java/team/aliens/dms_android/feature/remains/RemainsApplicationScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailsScreen.kt
- presentation/src/main/java/team/aliens/dms_android/widget/meal/MealService.kt
- presentation/src/main/java/team/aliens/dms_android/widget/meal/MealState.kt
- presentation/src/main/java/team/aliens/dms_android/widget/meal/MealType.kt
- presentation/src/main/java/team/aliens/dms_android/widget/meal/provider/BaseMealWidgetProvider.kt
- remote/src/main/java/team/aliens/remote/model/remains/FetchRemainsApplicationTimeResponse.kt
> 안드로이드 6.0 호환을 위한 작업을 수행하였습니다
- project property의 버전명을 변경하였습니다
- 최소 sdk level을 기존 26 -> 23으로 하향하였습니다 (android 8.0 to android 6.0)
- 일부 스크린의 navigation 로직을 리팩토링하였습니다
> 🔀:: (#447) 안드로이드 6.0 호환

- presentation/src/main/java/team/aliens/dms_android/base/BaseMviViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/base/BaseViewModel1.kt
- presentation/src/main/java/team/aliens/dms_android/base/MviSideEffect.kt
- presentation/src/main/java/team/aliens/dms_android/base/MviState.kt
- presentation/src/main/java/team/aliens/dms_android/base/MviViewState.kt
- presentation/src/main/java/team/aliens/dms_android/base/Reducer.kt
- presentation/src/main/java/team/aliens/dms_android/base/_MviState.kt
- presentation/src/main/java/team/aliens/dms_android/extension/rememberFlowWithLifeCycle.kt
- presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/ChangePasswordState.kt
- presentation/src/main/java/team/aliens/dms_android/feature/image/ConfirmImageState.kt
- presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomState.kt
> MVI ViewModel을 수정하였습니다
- flow 확장 함수 구현
- Mvi VIewModel 수정 (orbit API 참조)
> 🔀 :: (#444) mvi viewmodel 수정

- buildSrc/src/main/kotlin/ProjectProperties.kt
> target sdk 레벨을 변경합니다
- 30 -> 33으로 변경하였습니다.
> 🔀 :: (#453) target sdk 버전 변경

- presentation/src/main/java/team/aliens/dms_android/feature/main/home/announcements/NoticeDetailsScreen.kt
- presentation/src/main/java/team/aliens/dms_android/feature/main/home/announcements/NoticeDetailsViewModel.kt
- presentation/src/main/java/team/aliens/dms_android/feature/main/mainNavigation.kt
> 공지사항 상세 mvi viewmodel 적용을 합니다.
- 공지사항 상세 스크린 수정
- 공지사항 상세 뷰 모델 mvi 적용
> 🔀 :: (#470) 공지사항 상세 mvi viewmodel 적용

- app/src/main/java/team/aliens/dms/android/app/navigation/DmsNavigator.kt
- feature/src/main/java/team/aliens/dms/android/feature/main/mypage/MyPageScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/main/navigation/MainNavigator.kt
- feature/src/main/java/team/aliens/dms/android/feature/point/PointHistoryScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/point/PointHistoryViewModel.kt
>마이페이지에서  상벌점 카드 클릭시 상벌점 내역으로 이동하게 구현하였습니다
-
> 🔀 :: (#653) 마이페이지 상벌점 카드 클릭 시 상벌점 내역으로 이동

- feature/src/main/java/team/aliens/dms/android/feature/findid/FindIdViewModel.kt
> 🔀 :: (#668) 아이디 찾기 데이터 수정

- feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationScreen.kt
>신청 페이지에 태그를 일시적으로 삭제했습니다. 태그 업데이트 로직이 없어 나중에 추가하여 업데이트 하겠습니다
-
> 🔀 :: (#679) 신청 페이지 태그 삭제

- feature/src/main/java/team/aliens/dms/android/feature/main/mypage/MyPageScreen.kt
> 🔀 :: (#677) 상벌점 박스 색상 변경

- feature/src/main/java/team/aliens/dms/android/feature/signup/1_EnterSchoolVerificationCodeScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/signup/4_EnterEmailVerificationCodeScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/signup/5_SetIdScreen.kt
>학교인증 코드, 이메일 인증 코드, 아이디 설정(학번) 인풋을 자동으로 넘기기 기능을 구현하였습니다.
-
> 🔗 :: (#690) 회원가입 인풋 자동으로 넘기기

- app/build.gradle.kts
- app/src/main/java/team/aliens/dms/android/app/MainActivity.kt
- gradle/libs.versions.toml
> 🔗 :: (#687) 인 앱 업데이트 기능 구현

- feature/src/main/java/team/aliens/dms/android/feature/main/announcement/AnnouncementListScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/notice/NoticeDetailsScreen.kt
- feature/src/main/res/values/strings.xml
> 🔗 :: (#684) 안내 상세 시간 파싱

- app/build.gradle.kts
- data/src/main/java/team/aliens/dms/android/data/outing/model/OutingApplicationTime.kt
- data/src/main/java/team/aliens/dms/android/data/outing/repository/OutingRepository.kt
- data/src/main/java/team/aliens/dms/android/data/outing/repository/OutingRepositoryImpl.kt
- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingApplicationScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingViewModel.kt
- network/src/main/java/team/aliens/dms/android/network/outing/model/OutingAvailableTimeResponse.kt
- shared/date/src/main/java/team/aliens/dms/android/shared/date/util/Utils.kt
>외출 신청 기능에서 생긴 버그를 수정하였습니다.
- 외출 일자 시간에 맞춰 변경
- 외출 신청 시간 띄우기
- 외출 시간 예외처리
- 외출 시간 오전 오후 시간 처리
> 🔗 :: (#692) 외출 신청 버그

- core/design-system/src/main/java/team/aliens/dms/android/core/designsystem/Picker.kt
- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingApplicationScreen.kt
- feature/src/main/res/values/strings.xml
>외출 신청 디자인을 수정하였습니다.
- Picker 추가
> 🔀 :: (#705) 외출 신청 디자인 수정

- core/design-system/src/main/java/team/aliens/dms/android/core/designsystem/Buttons.kt
- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingApplicationScreen.kt
>외출 신청 버튼이 키보드 위로 안올라오는 버그를 수정하였습니다.
-
> 🔀 :: (#699) 외출 신청 버튼 수정

- core/design-system/src/main/java/team/aliens/dms/android/core/designsystem/Buttons.kt
- feature/src/main/java/team/aliens/dms/android/feature/editprofile/EditProfileImageScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/findid/FindIdScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingApplicationScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingStatusScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/signup/7_SetProfileImageScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/studyroom/details/StudyRoomDetailsScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/studyroom/list/StudyRoomListScreen.kt
>디자인시스템 Button에 private 접근제한자를 추가하였습니다.
- 접근제한자 추가
> 🔀 :: (#702) 디자인시스템 버튼 접근 제한자 변경

- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
>파이어베이스 Crashlytics 추가하여 버그를 순조롭게 찾습니다.
- 파이어베이스 Crashlytics 추가
> 🔀 :: (#716) 파이어베이스 crasslytics 추가

- core/design-system/src/main/java/team/aliens/dms/android/core/designsystem/DmsIcon.kt
- core/design-system/src/main/res/drawable/ic_person.xml
- feature/src/main/java/team/aliens/dms/android/feature/main/Main.kt
> 🔀 :: (#714) 마이페이지 아이콘 변경

- feature/src/main/java/team/aliens/dms/android/feature/notification/settings/NotificationSettingsScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/notification/settings/NotificationSettingsViewModel.kt
> 🔀 :: (#719) 알림 설정 페이지 토스트 제거

- app/build.gradle.kts
> Release v1.3.8

- core/datastore/src/main/java/team/aliens/dms/android/core/datastore/DataStore.kt
- core/datastore/src/main/java/team/aliens/dms/android/core/datastore/Qualifier.kt
- core/datastore/src/main/java/team/aliens/dms/android/core/datastore/di/DataStoreModule.kt
- core/device/src/main/java/team/aliens/dms/android/core/device/datastore/store/DeviceStoreImpl.kt
- core/jwt/src/main/java/team/aliens/dms/android/core/jwt/datastore/store/JwtStoreImpl.kt
- core/school/src/main/java/team/aliens/dms/android/core/school/datastore/store/FeaturesStoreImpl.kt
> 🔀 :: (#725) 로그아웃 후 로그인 시 로그인 안됨

- core/widget/src/main/java/team/aliens/dms/android/core/widget/meal/MealGlanceWidget.kt
- core/widget/src/main/java/team/aliens/dms/android/core/widget/meal/MealInfoStateDefinition.kt
> 🔀 :: (#729) 위젯 클릭 시 앱 이동

- app/build.gradle.kts
- buildSrc/src/main/kotlin/ProjectProperties.kt
> 🔀 :: (#734) 타켓 sdk version 업데이트

- data/src/main/java/team/aliens/dms/android/data/auth/mapper/AuthMapper.kt
- data/src/main/java/team/aliens/dms/android/data/meal/mapper/MealMapper.kt
- data/src/main/java/team/aliens/dms/android/data/notice/mapper/NoticeMapper.kt
- data/src/main/java/team/aliens/dms/android/data/point/mapper/PointMapper.kt
- data/src/main/java/team/aliens/dms/android/data/remains/mapper/RemainsMapper.kt
- data/src/main/java/team/aliens/dms/android/data/school/mapper/SchoolMapper.kt
- data/src/main/java/team/aliens/dms/android/data/student/mapper/StudentMapper.kt
- data/src/main/java/team/aliens/dms/android/data/studyroom/mapper/StudyRoomMapper.kt
> 🔀 :: (#658) 매핑 함수 private으로 전체 변환

- app/build.gradle.kts
- app/proguard-rules.pro
>R8을 적용하여 앱 축소, 난독화 및 최적화를 하였습니다.
수정 전
수정 후
APK size 181.MB -> 8.2MB
Download Size 16.3MB -> 6.5MB
-
> 🔀 :: (#703) 빌드 최적화

- core/design-system/src/main/java/team/aliens/dms/android/core/designsystem/Picker.kt
- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingApplicationScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingStatusScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingViewModel.kt
- feature/src/main/res/values/strings.xml
>외출 신청하는 시간에만 신청할 수 있도록 변경하였습니다.
-
> 🔀 :: (#741) 외출 신청 시간 설정

- buildSrc/src/main/kotlin/ProjectProperties.kt
> Release v1.3.9

- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingApplicationScreen.kt
- feature/src/main/java/team/aliens/dms/android/feature/outing/OutingViewModel.kt
- feature/src/main/res/values/strings.xml
> 🔀 :: (#746) 외출 버그 수정

- .gitignore
- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- buildSrc/src/main/kotlin/ProjectProperties.kt
> Release v1.4.0
