team-aliens/DMS-Android

presentation/src/main/java/com/example/dms_android/feature/auth/selfconfirmation/SelfConfirmScreen.kt
presentation/src/main/java/com/example/dms_android/feature/auth/selfconfirmation/VeritificationScreen.kt
presentation/src/main/res/values/strings.xml

> 본인확인 인증 뷰를 구현합니다.
-  본인확인 인증뷰를 크게 두 화면으로 나누어서 작업하였습니다.(아래)
- OTP, TextField있는 화면
시

🔀 :: FirstSprint  Self-confirmation and authentication View

---

auth_data/src/main/java/com/example/auth_data/remote/api/StudentsApi.kt
auth_data/src/main/java/com/example/auth_data/remote/datasource/declaration/RemoteStudentsDataSource.kt
auth_data/src/main/java/com/example/auth_data/remote/datasource/implementation/RemoteStudentsDataSourceImpl.kt
auth_data/src/main/java/com/example/auth_data/remote/response/students/ExamineGradeResponse.kt
auth_data/src/main/java/com/example/auth_data/remote/url/DmsUrl.kt
auth_data/src/main/java/com/example/auth_data/repository/StudentsRepositoryImpl.kt
auth_domain/src/main/java/com/example/auth_domain/entity/ExamineGradeEntity.kt
auth_domain/src/main/java/com/example/auth_domain/param/ExamineGradeParam.kt
auth_domain/src/main/java/com/example/auth_domain/repository/StudentsRepository.kt
auth_domain/src/main/java/com/example/auth_domain/usecase/students/DuplicateCheckEmailUseCase.kt
auth_domain/src/main/java/com/example/auth_domain/usecase/students/DuplicateCheckIdUseCase.kt
auth_domain/src/main/java/com/example/auth_domain/usecase/students/ExamineGradeUseCase.kt

> 학번검사 비즈니스로직 구현
- 학번검사 비즈니스 로직 작성
- 기존 코드 조금의 리팩토링
- 이메일체크 ,아이디 체크 UseCase의 네이밍을 수정하였습니다.
api 명세에 추가되어 작성했습니다.

🔀 :: 학번 검사 비즈니스 로직 구현

---

buildSrc/src/main/kotlin/Dependency.kt
buildSrc/src/main/kotlin/Versions.kt
presentation/build.gradle.kts
presentation/src/main/java/com/example/dms_android/base/BaseActivity.kt
presentation/src/main/java/com/example/dms_android/base/BaseFragment.kt
presentation/src/main/java/com/example/dms_android/feature/MainActivity.kt
presentation/src/main/res/layout/activity_main.xml

> jetpack compose 프로젝트를 xml + compose 프로젝트로 만들어줍니다.
- BaseActivity, BaseFragment를 추가해주었습니다.
- activity_main.xml, MainActivity xml 세팅 
- glide 의존성 추가 
- dataBinding 추가
- Navigation UI, FRAGMENT 의존성 추가
국밥 버억

🔀 :: migration compose to xml

---

presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/EmailCertificationFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/EnterEmailFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/id/SetIdFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/PolicyFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/last/SetProfileImageFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/password/SetPasswordFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/ConfirmSchoolFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/SchoolCertificationFragment.kt

> 이전 프로젝트 패키지 이름 변경 작업에서, Register 로직과 관련된 각 프래그먼트에 명시되어 있던 `@AndroidEntryPoint` 애너테이션이 누락되었고, 해당 프래그먼트에 접근하는 경우 앱이 종료되는 현상을 해결합니다.
- Register 로직과 관련된 각 프래그먼트에 `@AndroidEntryPoint` 애너테이션을 명시하였습니다
- .

🔀 :: (#190) Add @AndroidEntrypoint annotations on fragments related to Register

---

data/src/main/java/team/aliens/data/remote/api/RemainApi.kt
data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteRemainDataSource.kt
data/src/main/java/team/aliens/data/remote/datasource/implementation/RemoteRemainDataSourceImpl.kt
data/src/main/java/team/aliens/data/remote/response/remain/FetchAvailableRemainTimeResponse.kt
data/src/main/java/team/aliens/data/remote/response/remain/FetchCurrentRemainOptionResponse.kt
data/src/main/java/team/aliens/data/remote/response/remain/FetchRemainOptionsResponse.kt
data/src/main/java/team/aliens/data/remote/url/DmsUrl.kt
data/src/main/java/team/aliens/data/repository/RemainRepositoryImpl.kt
di/src/main/java/team/aliens/di/NetWorkModule.kt
di/src/main/java/team/aliens/di/RepositoryModule.kt
domain/src/main/java/team/aliens/domain/entity/remain/AvailableRemainTimeEntity.kt
domain/src/main/java/team/aliens/domain/entity/remain/CurrentRemainOptionEntity.kt
domain/src/main/java/team/aliens/domain/entity/remain/RemainOptionsEntity.kt
domain/src/main/java/team/aliens/domain/repository/RemainRepository.kt
domain/src/main/java/team/aliens/domain/usecase/remain/RemoteFetchAvailableRemainTimeUseCase.kt
domain/src/main/java/team/aliens/domain/usecase/remain/RemoteFetchCurrentRemainOptionsUseCase.kt
domain/src/main/java/team/aliens/domain/usecase/remain/RemoteFetchRemainOptionsUseCase.kt
domain/src/main/java/team/aliens/domain/usecase/remain/RemoteUpdateRemainOptionUseCase.kt

> 서버 통신을 위한 추상적인 도메인 엔티티, 리포지토리를 추가하고, 데이터 레이어에서 구현합니다.
- 잔류에 관한 엔티티 구현
- 잔류에 관한 리포지토리 구현
- 잔류에 관한 유즈케이스 구현
- 잔류에 관한 리포지토리 구현체 구현
- 잔류에 관한 API 인터페이스, URL 구현 및 의존성 주입 설정
- 잔류에 관한 DataSource 인터페이스, 구현체 구현 및 의존성 주입 설정
- NetworkModule에 RemainApi 제공 로직 구현
- RepositoryModule에 RemainRepository 바인딩 로직 구현

🔀 :: (#201) implement remain entities and repositories in domain and data layer

---

data/src/main/java/team/aliens/data/intercepter/AuthorizationInterceptor.kt
data/src/main/java/team/aliens/data/intercepter/OkHttpClientQualifier.kt
data/src/main/java/team/aliens/data/intercepter/TokenReissueClient.kt
data/src/main/java/team/aliens/data/remote/url/DmsHttpProperties.kt
data/src/main/java/team/aliens/data/remote/url/DmsUrlProperties.kt
di/src/main/java/team/aliens/di/NetWorkModule.kt
local_database/src/main/java/team/aliens/local_database/storage/implementation/UserDataStorageImpl.kt

> 토큰 저장 오류 및 BASE_URL이 노출되던 기존의 Interceptor를 리팩터합니다.
- 토큰 재발급을 위한 OkHttpClient 하위 구현체인 `TokenReissueClient`를 구현하였습니다
- `AuthorizationInterceptor`에서 `TokenReissueClient`를 주입받아, 토큰 재발급이 필요한 시점에 해당 Client를 Invoke하여 토큰 리스폰스(`SignInResponse`)를 전달받으며, 해당 정보를 로컬 데이터베이스에 저장합니다
- 아직 할 일이 많이 남아 있어욥..

🔀 :: (#207) refactor intercepter

---

di/src/main/java/team/aliens/di/NetWorkModule.kt
presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/navigator/NavigationRoute.kt
presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootDms.kt
presentation/src/main/java/team/aliens/dms_android/feature/splash/Splash.kt
presentation/src/main/java/team/aliens/dms_android/feature/splash/SplashActivity.kt
presentation/src/main/java/team/aliens/dms_android/feature/splash/SplashScreen.kt
presentation/src/main/res/values/strings.xml

> 로그인 화면, 메인 화면 등에서 뒤로가기 버튼을 눌러 즉시 앱이 종료되어야 할 상황에, 앱이 종료되지 않은 채 이전 스크린이 남아있는 버그를 수정합니다.
- 스플래시 화면이 backStack에 남아있는 문제를 수정하였습니다
- Login 화면이 Main 화면에서 뒤로가기 버튼을 눌렀을 때 유지되는 문제를 수정하였습니다
- 비밀번호 변경 텍스트를 눌렀을 때, 해당 스크린으로 이동하는 로직을 구현하였습니다
- LoginScreen을 리팩토링 하였습니다
- Composable 함수 다중 호출로 인한 복잡한 상태 관리를 최적화하기 위해, 기존의 뷰를 각기 다른 composable 함수에서 뷰를 구성하였던 로직을 평탄화?(flatten) 하였습니다

🔀 :: (#208) fix screen remaining bug when back button pressed

---

presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/CafeteriaScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/navigator/BottomNavigationItem.kt
presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt

> 급식 화면의 공지 알림 컴포넌트 아이콘을 클릭했을때 공지 화면으로 전환되는 로직을 구현했습니다.
- CafeterialScreen 파라미터로 moveToNoticeScreen 함수 추가
- bottomSelectedItem 값 BottomNavBar 함수에서 DmsApp 함수로 이동
- 공지 화면으로 이동 시 공지 바텀 아이템 선택 효과 구현
- 추후에 공지 알림을 상황에 따라 표시해주는 로직 구현이 필요할것 같습니다.
- ex 공지가 없는 경우 공지 알림 표시 X
- ex 유저가 공지 알림을 통해 새 공지를 확인한 경우 공지 알림 표시 X

🔀 :: (#210) implement floating notice click event

---

design-system/src/main/java/team/aliens/design_system/component/notice.kt
presentation/src/main/java/team/aliens/dms_android/feature/notice/NoticeScreen.kt

> notice screen 과 application screen 상단 text padding 을 통일했습니다
- 상단 text padding 통일
- notice screen 최신순 버튼 크기 수정
- notice item 클릭 시 ripple shape 수정
- 공지 목록에서 제목이 2줄 이상일시 padding 조절
Closes #230

🔀 :: (#230) edit top padding of application screen and notice screen

---

presentation/src/main/java/team/aliens/dms_android/feature/register/event/school/ConfirmSchoolEvent.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/event/school/ExamineSchoolCodeEvent.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/EnterEmailFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/id/SetIdFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/password/SetPasswordFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/ConfirmSchoolFragment.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/school/SchoolCertificationFragment.kt
presentation/src/main/java/team/aliens/dms_android/util/LifeCycle.kt
presentation/src/main/java/team/aliens/dms_android/util/View.kt
presentation/src/main/java/team/aliens/dms_android/viewmodel/auth/register/school/ConfirmSchoolViewModel.kt
presentation/src/main/java/team/aliens/dms_android/viewmodel/auth/register/school/ExamineSchoolCodeViewModel.kt

> 학교 인증 코드, 학교 확인 질문 코드를 리팩토링했습니다.
- LifeCycle.kt : Fragment를 위한 repeatOnStarted 함수를 만들어주었습니다.
- View.kt : Visible 로직 제거 (isVisible로 대체 가능)
- ExamineSchoolCodeEvent.kt : 필요없는 이벤트 제거 및 네이밍 변경
- ExamineSchoolCodeViewModel.kt : 바뀐 이벤트에 따라 이벤트 처리 수정
- SchoolCertificationFragment.kt : collect 처리 로직 수정
- ConfirmSchoolEvent.kt : 필요없는 이벤트 제거 및 네이밍 변경
- ConfirmSchoolViewModel.kt : 바뀐 이벤트에 따라 이벤트 처리 수정
- ConfirmSchoolFragment.kt : TextWacher 로직 개선 및 로직 수정
- EnterEmailFragment.kt, SetIdFragment.kt, SetPasswordFragment.kt : visible로직 제거함으로 인해 isVisible로 대체
추후에 Fragment 이동 로직, 값 넘기는 로직만 따로 PR파서 수정할 예정입니다.
많이 마음에 안 들고 안 좋은 코드들이 많지만
시간이 많지 않아 간단히 수정하는 정도만 진행했습니다.

🔀 :: (#227) refactor ExamineSchoolCode, ConfirmSchool 

---

presentation/src/main/java/team/aliens/dms_android/component/AppLogo.kt
presentation/src/main/java/team/aliens/dms_android/feature/auth/changepassword/SuccessChangePasswordScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/auth/comparepassword/ComparePasswordScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/remain/RemainApplicationScreen.kt
presentation/src/main/java/team/aliens/dms_android/util/TopBar.kt
presentation/src/main/java/team/aliens/dms_android/viewmodel/remain/RemainApplicationViewModel.kt
presentation/src/main/res/drawable/ic_success_change_password.xml
presentation/src/main/res/values/strings.xml

> 현재 비밀번호 인증 화면과 비밀번호 변경 성공 화면을 퍼블리싱 했습니다.
- ComparePasswordScreen 퍼블리싱
- SuccessChangePasswordScreen 퍼블리싱
- Dms Logo 컴포넌트 생성
- 잔류 신청 화면에서 "알 수 없음" 오류가 뜨는 버그를 수정했습니다.
- 비즈니스 로직은 아직 구현하지 않아서 비밀번호 변경 로직 머지 후 통합하여 리팩토링 및 비즈니스 로직 작성할 계획입니다

🔀 :: (#249) implement verify current password screen

---

design-system/src/main/java/team/aliens/design_system/dialog/dialog.kt
presentation/src/main/java/team/aliens/dms_android/feature/image/ConfirmImageScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/image/GettingImageOptionDialog.kt
presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt

> 사진 선택의 모달의 배경을 눌렀을 때 다이얼로그가 취소되도록 합니다
- 사진 선택 모달의 배경을 눌렀을 때 다이얼로그 취소 로직 구현

🔀 :: (#280) implement dialog dismissing when background pressed

---

presentation/src/main/java/team/aliens/dms_android/feature/cafeteria/MealContent.kt

> 현재 시간에 따라 앱에 처음 진입했을때 급식 뷰페이저의 최초 페이지가 설정되는 로직을 구현했습니다.
- 현재 시간이 0~8 인 경우 -> 아침
- 현재 시간이 9~13 인 경우 -> 점심
- 그 외의 경우 -> 저녁

🔀 :: (#337) implement meal pager set by current time

---

data/src/main/java/team/aliens/data/remote/api/StudyRoomApi.kt
data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteStudyRoomDataSource.kt
data/src/main/java/team/aliens/data/remote/datasource/implementation/RemoteStudyRoomDataSourceImpl.kt
data/src/main/java/team/aliens/data/remote/response/studyroom/StudyRoomAvailableTimeListResponse.kt
data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
design-system/src/main/java/team/aliens/design_system/dialog/dialog.kt
domain/src/main/java/team/aliens/domain/entity/studyroom/StudyRoomAvailableTimeListEntity.kt
domain/src/main/java/team/aliens/domain/param/ApplyStudyRoomParam.kt
domain/src/main/java/team/aliens/domain/param/StudyRoomDetailParam.kt
domain/src/main/java/team/aliens/domain/repository/StudyRoomRepository.kt
domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteApplySeatUseCase.kt
domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteCancelApplySeatUseCase.kt
domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteFetchStudyRoomDetailUseCase.kt
domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteFetchStudyRoomListUseCase.kt
presentation/src/main/java/team/aliens/dms_android/feature/image/ConfirmImageScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/navigator/NavigationRoute.kt
presentation/src/main/java/team/aliens/dms_android/feature/navigator/RootDms.kt
presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListUiState.kt
presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomListViewModel.kt
presentation/src/main/java/team/aliens/dms_android/viewmodel/image/ConfirmImageViewModel.kt
presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailUiState.kt
presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt
presentation/src/main/res/values/strings.xml

> 자습실 이용시간에 따른 목록 조회 / 신청 / 취소 / 상세보기 로직을 리팩토링 했습니다
- 조회 / 신청 / 취소 / 상세보기 로직에 uuid 파라미터 추가
- 이용 시간 목록 조회 로직 및 뷰 리팩토링
- 프로필 이미지 변경 로직 중복 요청 방지를 위한 버튼 비활성화 로직 구현
- UUID 에 null 처리는 이용 시간이 설정되어 있지 않은 학교의 경우 이용 시간 값을 null 로 보내야 하기 때문입니다.
- 자습실 상세보기에서 자리 컬러가 검정색인 경우 글자가 보이지 않습니다 (배경 색과 동일해서 그런걸로 추정)

🔀 :: (#333) refactor fetch studyroom list logic

---

presentation/src/main/java/team/aliens/dms_android/common/CompositionLocal.kt
presentation/src/main/java/team/aliens/dms_android/feature/MainActivity.kt
presentation/src/main/java/team/aliens/dms_android/feature/auth/login/LoginScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/mypage/MyPageScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/navigator/DmsApp.kt

> 로그인 화면에서 메인 화면으로 진입할 때, 사용 가능 기능에 따라 화면이 제대로 구성되지 않는 버그를 고칩니다.
- LoginScreen, DmsApp에 잘못된 composition local을 수정하였습니다
pr 메시지 잘 쓰겠습니다..

🔀 :: (#367) 로그인 후 처음 화면 진입시 비정상 종료 해결

---

data/src/main/java/team/aliens/data/remote/api/StudyRoomApi.kt
data/src/main/java/team/aliens/data/remote/datasource/declaration/RemoteStudyRoomDataSource.kt
data/src/main/java/team/aliens/data/remote/datasource/implementation/RemoteStudyRoomDataSourceImpl.kt
data/src/main/java/team/aliens/data/remote/url/DmsUrl.kt
data/src/main/java/team/aliens/data/repository/StudyRoomRepositoryImpl.kt
domain/src/main/java/team/aliens/domain/param/CancelStudyRoomParam.kt
domain/src/main/java/team/aliens/domain/repository/StudyRoomRepository.kt
domain/src/main/java/team/aliens/domain/usecase/studyroom/RemoteCancelApplySeatUseCase.kt
presentation/src/main/java/team/aliens/dms_android/feature/studyroom/StudyRoomDetailScreen.kt
presentation/src/main/java/team/aliens/dms_android/viewmodel/studyroom/StudyRoomDetailsViewModel.kt

> 자습실 자리 취소 시 전체 취소 오류가 뜨는 것을 수정했습니다.
- CancelStudyRoomParam을 추가하였습니다
- 서버에서 추가된 path를 추가하였습니다.
- 자습실 자리 취소 비즈니스 로직을 추가하였습니다.

🔀 :: (#376) 자습실 자리 취소 시 전체 취소 오류 수정

---

presentation/src/main/java/team/aliens/dms_android/_base/BaseViewModel.kt
presentation/src/main/java/team/aliens/dms_android/_base/ErrorEvent.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailScreen.kt
presentation/src/main/java/team/aliens/dms_android/feature/register/ui/email/SignUpEmailVerifyScreen.kt
presentation/src/main/java/team/aliens/dms_android/viewmodel/auth/register/email/RegisterEmailViewModel.kt
presentation/src/main/res/values/strings.xml

> 회원가입 이메일 인증 과정에서 발생하는 예외 처리 및 잔버그를 수정했습니다.
- currentBackStackEntry 중복 선언 수정
- requestEmailCode / checkEmailCode 함수에서 Conflict 분기 처리문 제거
- baseviewmodel timeoutexception 예외 처리 추가
- 인증코드 입력 화면 버튼 간격 버그 수정

🔀 :: (#374) 회원가입 이메일 요청 중복 처리 예외 버그 수정

---

presentation/src/main/java/team/aliens/dms_android/feature/application/DmsAppState.kt

> 앱 전역 상태 관리를 위한 DmsAppState 및 rememberDmsAppState() 를 구현하였습니다.
- rememberDmsAppState() 구현
- 내부 showToast() 및 navigateToRoute() 구현
- 내부 setDialogState() 구현
추가로 bottomSheetDialog 의 전역 관리가 필요할 것 같습니다

🔀 :: (#406) dmsappstate 구현

---

design-system/src/main/java/team/aliens/design_system/typography/typography.kt

> 기기에 따라 bottom navigation의 text가 깨지는 현상을 수정합니다
- typography 글씨 크기 계산 로직 구현

🔀 :: (#468) 기기에-따라-bottom-navigation의-text가-깨지는-버그-수정

---

feature/src/main/java/team/aliens/dms/android/feature/point/PointHistoryViewModel.kt

>상벌점 카드 클릭 시 상벌점 페이지 이동 하였을때 태그를 바꾸면 데이터를 불러오지 못함
- api 호출하는 pointType을 파라미터로 받아오는 값을 PointType.ALL로 수정하여 전체 데이터를 불러와서 처리하도록 바꿈

🔀 :: (#671) 상벌점 카드 클릭 시 상벌점 페이지 버그

---

feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationScreen.kt
feature/src/main/java/team/aliens/dms/android/feature/main/application/ApplicationViewModel.kt
feature/src/main/java/team/aliens/dms/android/feature/remains/RemainsApplicationScreen.kt

🔗 :: (#657) 신청화면 잔류신청하기 태그 업데이트 안됨
